saagie/gradle-saagie-dataops-plugin

.travis.yml
build.gradle
gradle.properties

feat: add auto increment

---

src/main/groovy/io/saagie/plugin/dataops/clients/SaagieClient.groovy
src/main/groovy/io/saagie/plugin/dataops/models/Server.groovy
src/main/groovy/io/saagie/plugin/dataops/utils/SaagieUtils.groovy
src/test/groovy/io/saagie/plugin/dataops/clients/SaagieClientTest.groovy

Feat: jwt option

---

src/main/groovy/io/saagie/plugin/dataops/DataOpsExtension.groovy
src/main/groovy/io/saagie/plugin/dataops/DataOpsModule.groovy
src/main/groovy/io/saagie/plugin/dataops/clients/SaagieClient.groovy
src/main/groovy/io/saagie/plugin/dataops/models/JobInstance.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/ProjectGetJobInstanceStatus.groovy
src/main/groovy/io/saagie/plugin/dataops/utils/SaagieUtils.groovy
src/test/groovy/io/saagie/plugin/DataOpsPluginTest.groovy
src/test/groovy/io/saagie/plugin/dataops/clients/SaagieClientTest.groovy

Feat: add projects get job instance status task

---

src/main/groovy/io/saagie/plugin/dataops/DataOpsExtension.groovy
src/main/groovy/io/saagie/plugin/dataops/DataOpsModule.groovy
src/main/groovy/io/saagie/plugin/dataops/clients/SaagieClient.groovy
src/main/groovy/io/saagie/plugin/dataops/models/PipelineInstance.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/ProjectGetPipelineInstanceStatusTask.groovy
src/main/groovy/io/saagie/plugin/dataops/utils/SaagieUtils.groovy
src/test/groovy/io/saagie/plugin/DataOpsPluginTest.groovy
src/test/groovy/io/saagie/plugin/dataops/clients/SaagieClientTest.groovy

feat: add getPipelineStatus task

---

src/main/groovy/io/saagie/plugin/dataops/clients/SaagieClient.groovy

fix: inconsistent behavior of updateJob  and updatePipeline

---

src/main/groovy/io/saagie/plugin/dataops/DataOpsModule.groovy
src/main/groovy/io/saagie/plugin/dataops/clients/SaagieClient.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/ProjectStopJobInstanceTask.groovy
src/main/groovy/io/saagie/plugin/dataops/utils/SaagieUtils.groovy
src/test/groovy/io/saagie/plugin/job/JobStopTaskTests.groovy
src/test/groovy/io/saagie/plugin/job/JobUpdateTaskTests.groovy

feat: add stopJobInstance task

---

src/main/groovy/io/saagie/plugin/dataops/DataOpsModule.groovy
src/main/groovy/io/saagie/plugin/dataops/clients/SaagieClient.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/ProjectArchiveJobTask.groovy
src/main/groovy/io/saagie/plugin/dataops/utils/SaagieUtils.groovy
src/test/groovy/io/saagie/plugin/job/JobArchiveTaskTests.groovy

feat: add projectsArchiveJob task

---

src/main/groovy/io/saagie/plugin/dataops/DataOpsModule.groovy
src/main/groovy/io/saagie/plugin/dataops/clients/SaagieClient.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/ProjectStopPipelineInstanceTask.groovy
src/main/groovy/io/saagie/plugin/dataops/utils/SaagieUtils.groovy
src/test/groovy/io/saagie/plugin/DataOpsPluginTest.groovy
src/test/groovy/io/saagie/plugin/pipeline/PipelineStopInstanceTaskTests.groovy

feat: add projectsStopPipelineInstance task

---

src/main/groovy/io/saagie/plugin/dataops/DataOpsModule.groovy
src/main/groovy/io/saagie/plugin/dataops/clients/SaagieClient.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/ProjectDeletePipelineTask.groovy
src/main/groovy/io/saagie/plugin/dataops/utils/SaagieUtils.groovy
src/test/groovy/io/saagie/plugin/pipeline/PipelineDeleteTaskTests.groovy

feat: add projectsDeletePipeline task

---

src/main/groovy/io/saagie/plugin/dataops/clients/SaagieClient.groovy
src/main/groovy/io/saagie/plugin/dataops/utils/SaagieUtils.groovy
src/test/groovy/io/saagie/plugin/project/ProjectListTaskTests.groovy

resolve #69 
https://github.com/saagie/gradle-saagie-dataops-plugin/issues/69#issuecomment-544411876

feat: add missing logs

---

src/main/groovy/io/saagie/plugin/dataops/models/Alerting.groovy
src/main/groovy/io/saagie/plugin/dataops/models/DockerInfos.groovy
src/main/groovy/io/saagie/plugin/dataops/models/ExposedPort.groovy
src/main/groovy/io/saagie/plugin/dataops/models/IMapable.groovy
src/main/groovy/io/saagie/plugin/dataops/models/Job.groovy
src/main/groovy/io/saagie/plugin/dataops/models/JobInstance.groovy
src/main/groovy/io/saagie/plugin/dataops/models/JobVersion.groovy
src/main/groovy/io/saagie/plugin/dataops/models/PackageInfo.groovy
src/main/groovy/io/saagie/plugin/dataops/models/Pipeline.groovy
src/main/groovy/io/saagie/plugin/dataops/models/PipelineInstance.groovy
src/main/groovy/io/saagie/plugin/dataops/models/PipelineVersion.groovy
src/main/groovy/io/saagie/plugin/dataops/models/Project.groovy
src/main/groovy/io/saagie/plugin/dataops/models/Resources.groovy
src/main/groovy/io/saagie/plugin/dataops/utils/SaagieUtils.groovy
src/test/groovy/io/saagie/plugin/job/JobCreateTaskTests.groovy
src/test/groovy/io/saagie/plugin/project/ProjectListTaskTests.groovy

This allow us to specify how the model should be parsed into JSON
resolve #70

feat: add a IMapable interface that all POJO must implements

---

src/main/groovy/io/saagie/plugin/dataops/DataOpsExtension.groovy
src/main/groovy/io/saagie/plugin/dataops/clients/SaagieClient.groovy
src/main/groovy/io/saagie/plugin/dataops/utils/SaagieUtils.groovy
src/test/groovy/io/saagie/plugin/dataops/clients/SaagieClientTest.groovy
src/test/groovy/io/saagie/plugin/job/JobGetInstanceStatusTaskTests.groovy
src/test/groovy/io/saagie/plugin/job/JobStopTaskTests.groovy

fix: update jobInstance key to be jobinstance

---

src/main/groovy/io/saagie/plugin/dataops/clients/SaagieClient.groovy
src/test/groovy/io/saagie/plugin/technology/TechnologyTests.groovy

fix(projectListTechnologies): remove duplicated technologies

---

src/main/groovy/io/saagie/plugin/dataops/models/Alerting.groovy
src/test/groovy/io/saagie/plugin/dataops/models/AlertingTests.groovy

Fix issue #63

---

src/main/groovy/io/saagie/plugin/dataops/models/Server.groovy
src/test/groovy/io/saagie/plugin/DataOpsPluginTest.groovy
src/test/groovy/io/saagie/plugin/platform/PlatformListTaskTests.groovy

fix: remove the required rule on environment

---

src/main/groovy/io/saagie/plugin/dataops/DataOpsExtension.groovy
src/main/groovy/io/saagie/plugin/dataops/clients/SaagieClient.groovy
src/main/groovy/io/saagie/plugin/dataops/utils/SaagieUtils.groovy
src/test/groovy/io/saagie/plugin/dataops/clients/SaagieClientTest.groovy
src/test/groovy/io/saagie/plugin/pipeline/PipelineGetInstanceStatusTaskTests.groovy
src/test/groovy/io/saagie/plugin/pipeline/PipelineStopInstanceTaskTests.groovy

fix: lowercased the i letter on jobinstance

---

src/main/groovy/io/saagie/plugin/dataops/DataOpsModule.groovy
src/main/groovy/io/saagie/plugin/dataops/clients/SaagieClient.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/ProjectsListAllPipelinesTask.groovy
src/main/groovy/io/saagie/plugin/dataops/utils/SaagieUtils.groovy
src/test/groovy/io/saagie/plugin/DataOpsPluginTest.groovy
src/test/groovy/io/saagie/plugin/pipeline/PipelineListAllTaskTests.groovy

- refactor the required params check
#68

feat: add projectsListAllPipelines task

---

src/main/groovy/io/saagie/plugin/dataops/DataOpsModule.groovy
src/main/groovy/io/saagie/plugin/dataops/clients/SaagieClient.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/TechnologyListTask.groovy
src/main/groovy/io/saagie/plugin/dataops/utils/SaagieUtils.groovy
src/test/groovy/io/saagie/plugin/technology/TechnologyListTests.groovy

feat: add technologyList task

---

src/main/groovy/io/saagie/plugin/dataops/DataOpsModule.groovy
src/main/groovy/io/saagie/plugin/dataops/clients/SaagieClient.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/group/GroupListTask.groovy
src/main/groovy/io/saagie/plugin/dataops/utils/SaagieUtils.groovy
src/test/groovy/io/saagie/plugin/group/GroupListTest.groovy

feat: add groupList task

---

src/main/groovy/io/saagie/plugin/dataops/DataOpsExtension.groovy
src/main/groovy/io/saagie/plugin/dataops/DataOpsModule.groovy
src/main/groovy/io/saagie/plugin/dataops/clients/SaagieClient.groovy
src/main/groovy/io/saagie/plugin/dataops/clients/SaagieClientUtils.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/group/GroupListTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/platform/PlatformListTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/artifact/ProjectsExportJobTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/artifact/ProjectsExportJobV1Task.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/artifact/ProjectsImportJobTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/jobInstance/ProjectGetJobInstanceStatusTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/jobInstance/ProjectStopJobInstanceTask.groovy
src/main/groovy/io/saagie/plugin/dataops/utils/HttpClientBuilder.groovy
src/main/groovy/io/saagie/plugin/dataops/utils/SaagieUtils.groovy
src/main/groovy/io/saagie/plugin/dataops/utils/ZipUtils.groovy
src/main/groovy/io/saagie/plugin/dataops/utils/directory/FolderGenerator.groovy
src/main/groovy/io/saagie/plugin/dataops/utils/directory/ZippingFolder.groovy

https://github.com/saagie/gradle-saagie-dataops-plugin/issues/238

Rename generated tmp files

---

src/main/groovy/io/saagie/plugin/dataops/clients/SaagieClient.groovy
src/test/groovy/io/saagie/plugin/tasks/artifacts/ArtifactsImportTaskTest.groovy

Fix artifact tmp file deletion

---

example/CreateJobRunIthenGetTheStatusUseCase/build.gradle
src/main/groovy/io/saagie/plugin/dataops/tasks/group/GroupListTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/platform/PlatformListTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/artifact/ProjectsExportJobTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/artifact/ProjectsExportJobV1Task.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/artifact/ProjectsImportJobTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/job/ProjectCreateJobTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/job/ProjectDeleteJobTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/job/ProjectListJobsTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/job/ProjectRunJobTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/job/ProjectUpgradeJobTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/jobInstance/ProjectGetJobInstanceStatusTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/jobInstance/ProjectStopJobInstanceTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/pipeline/ProjectCreatePipelineTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/pipeline/ProjectDeletePipelineTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/pipeline/ProjectRunPipelineTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/pipeline/ProjectUpgradePipelineTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/pipeline/ProjectsListPipelinesTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/pipelineInstance/ProjectGetPipelineInstanceStatusTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/pipelineInstance/ProjectStopPipelineInstanceTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/project/ProjectDeleteTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/project/ProjectListTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/project/ProjectsCreateTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/project/ProjectsUpdateTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/technology/ProjectListTechnologiesTask.groovy
src/main/groovy/io/saagie/plugin/dataops/tasks/projects/technology/TechnologyListTask.groovy

We need to find a way to script a sequences of tasks in a gradle build, and to do so we need to make some changes in the current plugin. We have to store each tasks result inside `result` variable. 
https://github.com/saagie/gradle-saagie-dataops-plugin/issues/287
Some tasks store result inside `result` variable
Some other store inside `resultData` 
Some others doesn't store the `result`
Add `result` to all tasks class that inherit from `DefaultTask` class avaible inside the project
contained inside the `groovy/io/saagie/plugin/dataops/tasks` folder
```
class ProjectGetPipelineInstanceStatusTask extends DefaultTask {
@Input DataOpsExtension configuration
@Input String taskName
@Internal SaagieClient saagieClient
def result // <===== add this line
@TaskAction
def …
```

[ Code integration in progress ] Fix Task Result InConsistencies - Unable to use for Automation

---

build.gradle.kts

https://github.com/saagie/gradle-saagie-dataops-plugin/issues/326
In this part i need to make sure the version inside the readme file update every time a new version is generated

Try fix readme update

---

src/main/groovy/io/saagie/plugin/dataops/clients/SaagieClient.groovy

https://github.com/saagie/gradle-saagie-dataops-plugin/issues/333
Add feature extract versions with the option "include_all_versions" when exporting artifact in the v2 app

feat-export-versions-v2

---

src/main/groovy/io/saagie/plugin/dataops/clients/SaagieClient.groovy
src/main/groovy/io/saagie/plugin/dataops/models/AppDTO.groovy
src/main/groovy/io/saagie/plugin/dataops/models/AppMapper.groovy
src/main/groovy/io/saagie/plugin/dataops/models/AppVersionDTO.groovy
src/main/groovy/io/saagie/plugin/dataops/models/ExportApp.groovy

```
@TypeChecked
class ExportApp implements IExists {
AppDTO appDTO = new AppDTO()
AppVersionDTO AppVersionDTO = new AppVersionDTO()
ArrayList<AppVersionDTO> versions = new ArrayList<AppVersionDTO>()
@Override
boolean exists() {
return appDTO.exists() && AppVersionDTO.exists()
}
void setAppFromApiResult(appDetailResult) {
AppDTO.setAppFromApiResult(appDetailResult)
}
void setAppVersionFromApiResult(version) {
appVersionDTO.setAppVersionFromApiResult(version)
}
}
void addAppVersionFromV2ApiResult(version) {
AppVersionDTO appVersionDTOElement = new AppVersionDTO()
appVersionDTOElement.setAppVersionFromApiResult(version)
versions.add(appVersionDTOElement)
}
```
```
class AppDTO extends JobDTO {
int storageSizeInMB;
void setAppFromApiResult(appDetailResult) {
this.storageSizeInMB = …
```

Feat add export app add entity
